name: Endurance Test v2

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
    inputs:
      yaml_file:
        description: '読み込むYAMLファイルの名前 (拡張子なし)'
        required: false
        default: 'weekdays'
      build_or_publish:
        description: 'ビルドまたは公開 (build または publish)'
        required: false
        type: choice
        options:
          - 'build'
          - 'publish'
        default: 'build'

env:
  test_dir: "C:/Hutzper/self_host_runner/CSharp.Hutzper.Library"
  repository_url: "https://github.com/Hutzper-inc/CSharp.Hutzper.Library.git"
  mekiki_project: "C:/Hutzper/self_host_runner/CSharp.Hutzper.Library/Hutzper.Library.FormsMekiki/Hutzper.Project.Mekiki.csproj"
  yaml_settings_dir: "C:/Hutzper/self_host_runner/CSharp.Hutzper.Library/test_endurance/settings"
  log_dir: "C:/Hutzper/self_host_runner/CSharp.Hutzper.Library/Hutzper.Library.FormsMekiki/bin/x64/log"
  base_results_dir: "C:/Hutzper/self_host_runner/CSharp.Hutzper.Library/test_endurance/result"
  vs_path: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/devenv.exe"

jobs:
  endurance_test_mekiki:
    runs-on: [self-hosted, windows]
    steps:
      - name: Get Current Timestamp and Date Suffix
        id: get_timestamp_and_suffix
        run: |
          $timestamp = (Get-Date -Format "yyyyMMdd-HHmmss")
          $dateSuffix = (Get-Date -Format "yyyyMMdd")
          echo "::set-output name=timestamp::$timestamp"
          echo "::set-output name=date_suffix::$dateSuffix"
        shell: powershell

      - name: Checkout Repository and Prepare Branch
        run: |
          $repoUrl = "${{ env.repository_url }}"
          $dir = "${{ env.test_dir }}"
          $branch = '${{ github.ref_name }}'
          if ($branch -eq 'main') {
            $branch = 'test_endurance'
          }

          if (-Not (Test-Path $dir)) {
            git clone $repoUrl $dir
          } else {
            Set-Location -Path $dir
            git fetch origin
            git checkout $branch
            git pull origin $branch
          }
        shell: powershell

      - name: Build or Publish Mekiki Project
        run: |
          $operation = '${{ github.event.inputs.build_or_publish }}'
          if (-Not $operation) {
            $operation = 'build'
          }

          $projectPath = "${{ env.mekiki_project }}"
          if ($operation -eq 'build') {
            dotnet build $projectPath -c Release
          } elseif ($operation -eq 'publish') {
            $outputDir = "${{ env.test_dir }}/publish"
            dotnet publish $projectPath -c Release -o $outputDir
          } else {
            throw "無効なオプションが指定されました。'build' または 'publish' を指定してください。"
          }
        shell: powershell

      - name: Install PowerShell-Yaml Module
        run: |
          Install-Module -Name powershell-yaml -Scope CurrentUser -Force
        shell: powershell

      - name: Read YAML File and Start Mekiki Tests
        run: |
          $yamlFileInput = '${{ github.event.inputs.yaml_file }}'
          if (-Not $yamlFileInput) {
            $yamlFileInput = 'weekdays'
          }
          $yamlFilePath = "${{ env.yaml_settings_dir }}/$yamlFileInput.yml"
          if (-Not (Test-Path $yamlFilePath)) {
            throw "YAMLファイル '$yamlFilePath' が存在しません。"
          }

          $processSettings = (Get-Content $yamlFilePath | ConvertFrom-Yaml)
          $timestamp = '${{ steps.get_timestamp_and_suffix.outputs.timestamp }}'
          $logFilePath = "${{ env.log_dir }}/$timestamp.log"
          $resultsFilePath = "${{ env.base_results_dir }}/$timestamp.txt"

          

          function Test-Process {
            param ($processSettings, $logFilePath, $resultsFilePath)
            $results = @()
            foreach ($test in $processSettings.cameras) {
              $endTime = (Get-Date).AddMinutes($test.duration_minutes)
              while ((Get-Date) -lt $endTime) {
                Start-Sleep -Seconds 5
                $logContent = Get-Content $logFilePath -Raw
                if ($logContent -match "異常") {
                  Write-Output "$($test.name) テスト中に異常が検知されました"
                  $results += "$($test.name): Failure"
                  break
                } else {
                  Write-Output "$($test.name) is running"
                }
              }
              if ($logContent -notmatch "異常") {
                $results += "$($test.name): Success"
              }
            }
            $results | Out-File $resultsFilePath
          }

          Test-Process -processSettings $processSettings -logFilePath $logFilePath -resultsFilePath $resultsFilePath
        shell: powershell
