name: Endurance Test

on:
  schedule:
    - cron: '0 22 * * *'  # 毎日22:00にプロセスを開始
  workflow_dispatch:
    inputs:
      zip_file:
        description: '読み込むYAMLファイルの名前 (拡張子なし)'
        required: false
        default: 'weekdays'
      build_or_publish:
        description: 'ビルドまたは公開 (build または publish)'
        required: false
        type: choice
        options:
          - 'build'
          - 'publish'
        default: 'build'

env:
  test_dir: "C:/Hutzper/self_host_runner/CSharp.Hutzper.Library"
  repository_url: "https://github.com/Hutzper-inc/CSharp.Hutzper.Library.git"
  mekiki_project: "C:/Hutzper/self_host_runner/CSharp.Hutzper.Library/Hutzper.Library.FormsMekiki/Hutzper.Project.Mekiki.csproj"
  test_settings_dir: "C:/Hutzper/self_host_runner/CSharp.Hutzper.Library/test_endurance/settings"
  mekiki_setting: "C:/Hutzper/self_host_runner/CSharp.Hutzper.Library/Hutzper.Library.FormsMekiki/bin"
  log_dir: "C:/Hutzper/self_host_runner/CSharp.Hutzper.Library/Hutzper.Library.FormsMekiki/bin/x64/log"
  test_results_dir: "C:/Hutzper/self_host_runner/CSharp.Hutzper.Library/test_endurance/result"
  vs_path: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/devenv.exe"

jobs:
  endurance_test_mekiki:
    runs-on: [self-hosted, windows]
    steps:
      - name: Get Current Timestamp and Date Suffix
        id: get_timestamp_and_suffix
        run: |
          $timestamp = (Get-Date -Format "yyyyMMdd-HHmmss")
          $dateSuffix = (Get-Date -Format "yyyyMMdd")
          echo "::set-output name=timestamp::$timestamp"
          echo "::set-output name=date_suffix::$dateSuffix"
        shell: powershell

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Prepare Mekiki Branch
        run: |
          $branch = '${{ github.ref_name }}'
          if ($branch -eq 'main') {
            $branch = 'test_endurance'
          }

          if (-Not (Test-Path "${{ env.test_dir }}")) {
            git clone ${{ env.repository_url }} ${{ env.test_dir }}
          } else {
            Set-Location -Path ${{ env.test_dir }}
            git fetch origin
            git checkout $branch
            git pull origin $branch
          }
        shell: powershell

      - name: Dotnet Build or Publish 
        run: |
          $operation = '${{ github.event.inputs.build_or_publish }}'
          if ($operation -eq '') {
            $operation = 'build'
          }

          if ($operation -eq 'build') {
            dotnet build ${{ env.mekiki_project }} -c Release
          } elseif ($operation -eq 'publish') {
            dotnet publish ${{ env.mekiki_project }} -c Release -o "${{ env.test_dir }}/publish"
          } else {
            Write-Error "無効なオプションが指定されました。'build' または 'publish' を指定してください。"
            exit 1
          }
        shell: powershell

      - name: Install PowerShell-Yaml Module
        run: |
          Install-Module -Name powershell-yaml -Scope CurrentUser -Force
        shell: powershell

      - name: Read YAML File and Run Tests
        run: |
          $timestamp = '${{ steps.get_timestamp_and_suffix.outputs.timestamp }}'
          $date_suffix = '${{ steps.get_timestamp_and_suffix.outputs.date_suffix }}'

          # 入力ファイルが指定されていなければデフォルト 'weekdays.yml' を使用
          $settingFileInput = '${{ github.event.inputs.zip_file }}'
          if($settingFileInput -eq '') {
            $settingFileInput = 'weekdays'
          }
          $yamlFileName = "$settingFileInput.yml"
          $yamlFilePath = "${{ env.test_settings_dir }}\$settingFileName"
          
          if (-Not (Test-Path $yamlFilePath)) {
            Write-Error "設定ファイル '$yamlFilePath' が存在しません。"
            exit 1
          }

          $yamlContent = Get-Content $yamlFilePath | Out-String
          $processSettings = $yamlContent | ConvertFrom-Yaml

          # 日付ごとのフォルダを作成
          $dateFolder = "${{ env.test_results_dir }}/$date_suffix"
          if (-Not (Test-Path $dateFolder)) {
            New-Item -Path $dateFolder -ItemType Directory | Out-Null
          }

          # テストごとのフォルダの作成
          $testsFolder = "$dateFolder/$timestamp"
          if (-Not (Test-Path $testsFolder)) {
            New-Item -Path $testsFolder -ItemType Directory | Out-Null
          }

          # 各テストの処理
          foreach ($test in $processSettings.cameras) {
            $zipFileName = "$($test.name).zip"
            $zipFilePath = "${{ env.test_settings_dir }}\$settingFileInput\$zipFileName"

            if (-Not (Test-Path $zipFilePath)) {
              Write-Error "ZIPファイル '$zipFilePath' が存在しません。"
              exit 1
            }

            # 必要なファイルの配置
            Remove-Item -Path "${{ env.mekiki_setting }}\x64" -Force -Recurse
            Copy-Item -Path $zipFilePath -Destination ${{ env.mekiki_setting }} -Force
            Expand-Archive -Path "${{ env.mekiki_setting }}\$zipFileName" -DestinationPath ${{ env.mekiki_setting }} -Force
            Remove-Item -Path "${{ env.mekiki_setting }}\$zipFileName" -Force

            Write-Output "Starting Mekiki application for test: $($test.name)..."
            if (-Not (Test-Path "${{ env.vs_path }}")) {
              Write-Error "Visual Studio のパスが見つかりません。"
              exit 1
            }

            # Mekikiプロジェクトの実行
            Start-Process -FilePath "${{ env.vs_path }}" -ArgumentList "`"$($env:mekiki_project)`" /Run" -NoNewWindow -PassThru | Out-Null
            Start-Sleep -Seconds 5

            # プロセス確認
            $processName = "Hutzper.Project.Mekiki"
            $endTime = (Get-Date).AddMinutes(1)

            while ((Get-Date) -lt $endTime) {
              $process = Get-Process -Name $processName -ErrorAction SilentlyContinue
              if ($process) {
                Write-Output "$processName is running."
                break
              }
              Start-Sleep -Seconds 5
            }

            if (-Not $process) {
              Write-Output "$processName has stopped within the 1-minute check period."
              exit 1
            }

            # テスト処理とログ確認
            $logFilePath = "${{ env.log_dir }}/$date_suffix.log"
            $startTime = Get-Date
            $endTime = $startTime.AddMinutes($test.duration_minutes)

            while ((Get-Date) -lt $endTime) {
              Start-Sleep -Seconds 5

              $logContent = Get-Content $logFilePath -Raw
              if ($logContent -match "異常") {
                Write-Host "::error::$($test.name)テスト中に異常が発生しました"
                exit 1
              } else {
                Write-Output "$($test.name)は正常に動作しています."
              }
            }

            # Visual Studioの停止
            Stop-Process -Name devenv -Force
          }

          Write-Output "すべてのテストが完了しました。"
        shell: powershell
