name: Manage and Monitor MS Paint Process

on:
  schedule:
    - cron: '0 22 * * *'
    - cron: '0 6 * * *'
    - cron: '*/5 22-23,0-5 * * *'
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (start, stop, check)'
        required: true
        default: 'check'

jobs:
  manage-and-monitor:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run PowerShell Script to Manage and Check Process
        id: manage_and_check_process
        shell: powershell
        run: |
          $Action = $env:INPUT_ACTION
          $currentHour = (Get-Date).Hour
          $IsManualTrigger = ${{ github.event_name == 'workflow_dispatch' }}
          
          Write-Output "[$(Get-Date)] Current Hour: $currentHour"
          Write-Output "[$(Get-Date)] Action: $Action"
          Write-Output "[$(Get-Date)] Is Manual Trigger: $IsManualTrigger"
          
          # デフォルトのアクション設定
          if (-not $Action) 
          {
            $Action = "check"
            Write-Output "[$(Get-Date)] Actionが指定されていないため、デフォルトの 'check' を使用します。"
          }

          # 手動実行かどうかを確認
          if ($IsManualTrigger) {
            # 手動実行の場合は時間制限なしで実行
            .\scripts\manage-and-check-process.ps1 -Action $Action
          } else {
            # スケジュール実行の場合は時間帯によって制御
            if ($Action -eq "start") {
              .\scripts\manage-and-check-process.ps1 -Action start
            } elseif ($Action -eq "stop") {
              .\scripts\manage-and-check-process.ps1 -Action stop
            } elseif ($Action -eq "check") {
              .\scripts\manage-and-check-process.ps1 -Action check
            } else {
              Write-Output "[$(Get-Date)] 無効なアクションまたはスケジュールです。"
              exit 1
            }
          }

      - name: Notify Process Management Status
        if: failure()
        run: echo "プロセス管理が失敗しました。詳細はログを確認してください。"
