name: Manage and Monitor Process

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (start, stop, check)'
        required: true
        default: 'check'
        type: string

jobs:
  manage-and-monitor:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Pull Latest Changes
        run: |
          git pull origin develop
        shell: bash

      - name: Run メキキオール (Send Shortcut Keys)
        run: |
          powershell -ExecutionPolicy Bypass -File "scripts/send_shortcut_keys.ps1"
        shell: powershell

      - name: Wait for 5 Minutes
        run: |
          Write-Output "5分間待機中..."
          Start-Sleep -Seconds 300
        shell: powershell

      - name: Check Specific Process
        id: check_process
        run: |
          # 特定のプロセスが実行中か確認します
          $process = Get-Process -Name "Hutzper.Library" -ErrorAction SilentlyContinue
          if ($process) {
            Write-Output "Hutzper.Library は実行中です。"
          } else {
            Write-Output "Hutzper.Library は停止しています。"
            exit 1
          }
        shell: powershell

      - name: Handle Failure
        if: failure()
        run: echo "プロセスが停止しているため、ジョブが失敗しました。"
