name: Manage and Monitor MS Paint Process

on:
  schedule:
    # 22時にプロセスを開始し、6時にプロセスを終了する設定
    - cron: '0 22 * * *'
    - cron: '0 6 * * *'
    # 5分ごとにプロセスの状態を確認
    - cron: '*/5 22-23,0-5 * * *'
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (start, stop, check)'
        required: true
        default: 'check'
      time:
        description: 'Time to execute the action (format: HH:mm)'
        required: true
        default: '00:00'

jobs:
  manage-and-monitor:
    runs-on: [self-hosted, windows]  # セルフホストランナーとWindows環境を指定

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run PowerShell Script to Manage and Check Process
        id: manage_and_check_process
        shell: powershell
        run: |
          $Action = "${{ github.event.inputs.action }}"
          $Time = if ($env:TIME) { [datetime]::ParseExact('${{ github.event.inputs.time }}', 'HH:mm', $null) } else { Get-Date }
          .\scripts\manage-and-check-process.ps1 -Action $Action -Time $Time

      - name: Notify Process Management
        if: failure()  # プロセス管理に失敗した場合
        run: |
          echo "MS Paint プロセスの管理に失敗しました。"
