name: Manage and Monitor MS Paint Process

on:
  schedule:
    - cron: '0 22 * * *'    # 22時にプロセスを開始
    - cron: '0 6 * * *'     # 6時にプロセスを終了
    - cron: '*/5 * * * *'   # 5分ごとにプロセスの状態を確認
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (start, stop, check)'
        required: true
        default: 'check'

jobs:
  manage-process:
    runs-on: [self-hosted, windows]  # セルフホストランナーとWindows環境を指定

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          echo "ACTION=${{ github.event.inputs.action }}" >> $GITHUB_ENV

      - name: Manage and Check MS Paint Process
        shell: pwsh
        run: |
          $Action = $env:ACTION
          $Time = Get-Date
          .\scripts\manage-and-check-process.ps1 -Action $Action -Time $Time
