name: Manage and Monitor test

on:
  #schedule:
    #- cron: '0 22 * * *'  # 毎日22:00にプロセスを開始
    #- cron: '*/10 22-23,0-5 * * *'  # 毎日22:10から6:00まで10分ごとに状態を確認
    #- cron: '0 6 * * *'  # 毎日6:00にプロセスを終了
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (start, check, stop)'
        required: true
        default: 'start'
        type: string

jobs:
  manage-process:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Prepare Project Directory
        run: |
          $projectDir = "C:\CSharp.Hutzper.Library"
          $repositoryUrl = "https://github.com/Hutzper-inc/CSharp.Hutzper.Library.git"
          
          if (-Not (Test-Path $projectDir)) {
            git clone $repositoryUrl $projectDir
          } else {
            Set-Location -Path $projectDir
            git pull origin develop
          }
        shell: powershell

      - name: Perform Action
        if: ${{ github.event.inputs.action == 'start' || github.event.schedule.cron == '0 22 * * *' }}
        run: |
          powershell -ExecutionPolicy Bypass -File "scripts/start_process.ps1"
        shell: powershell

      - name: Check Process
        if: ${{ github.event.inputs.action == 'check' || github.event.schedule.cron == '*/10 22-23,0-5 * * *' }}
        run: |
          powershell -ExecutionPolicy Bypass -File "scripts/check_process.ps1"
        shell: powershell

      - name: Handle Failure
        if: failure()
        run: |
          echo "プロセスが停止しているため、ジョブが失敗しました。"
        shell: powershell

      - name: Stop Process
        if: ${{ github.event.inputs.action == 'stop' || github.event.schedule.cron == '0 6 * * *' }}
        run: |
          powershell -ExecutionPolicy Bypass -File "scripts/stop_process.ps1"
        shell: powershell
