name: Manage and Monitor MS Paint Process

on:
  schedule:
    # 5分ごとにプロセスの状態を確認
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (start, stop, check)'
        required: true
        default: 'check'
      time:
        description: 'Time to execute the action (format: HH:mm)'
        required: true

jobs:
  manage-process:
    runs-on: [self-hosted, windows]  # セルフホストランナーとWindows環境を指定

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          echo "ACTION=${{ github.event.inputs.action }}" >> $GITHUB_ENV
          echo "TIME=${{ github.event.inputs.time }}" >> $GITHUB_ENV

      - name: Manage and Check MS Paint Process
        shell: powershell
        run: |
          $Action = $env:ACTION
          try {
            # TIMEの形式を検証し、適切なDateTimeオブジェクトに変換
            if ($env:TIME -match '^\d{2}:\d{2}$') {
              $Time = [datetime]::ParseExact($env:TIME, 'HH:mm', $null)
            } else {
              throw "指定されたTIMEの形式が正しくありません: $env:TIME"
            }
          } catch {
            Write-Error "時間の変換エラー: $_"
            exit 1
          }
          .\scripts\manage-and-check-process.ps1 -Action $Action -Time $Time
