- name: Run PowerShell Script to Manage and Check Process
  id: manage_and_check_process
  shell: powershell
  run: |
    $Action = $env:ACTION
    $currentHour = (Get-Date).Hour
    Write-Output "[$(Get-Date)] Current Hour: $currentHour"
    Write-Output "[$(Get-Date)] Action: $Action"
    
    # デフォルトのアクション設定を追加
    if (-not $Action) {
        $Action = "check"
        Write-Output "[$(Get-Date)] Actionが指定されていないため、デフォルトの 'check' を使用します。"
    }
    
    if ($currentHour -eq 22 -and $Action -eq "start") {
      .\scripts\manage-and-check-process.ps1 -Action start
    } elseif ($currentHour -eq 6 -and $Action -eq "stop") {
      .\scripts\manage-and-check-process.ps1 -Action stop
    } elseif ($Action -eq "check") {
      .\scripts\manage-and-check-process.ps1 -Action check
    } else {
      Write-Output "[$(Get-Date)] 無効なアクションまたはスケジュールです。"
      exit 1
    }
