name: Manage and Monitor Process

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (start, stop, check)'
        required: true
        default: 'check'
        type: string

jobs:
  manage-and-monitor:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Git Remote URL
        run: |
          git remote set-url origin https://github.com/yoshinari0508/DailyEnduranceTest.git
        shell: bash

      - name: Pull Latest Changes from develop Branch
        run: |
          # PowerShell スクリプトを実行するためのディレクトリを設定
          $repoDir = "C:\Users\shohei.yoshinari_hut\CSharp.Hutzper.Library"

          # 指定したディレクトリに移動
          Set-Location -Path $repoDir

          # リモートリポジトリから develop ブランチをフェッチしてプル
          git fetch origin develop
          git pull origin develop
        shell: powershell

      - name: Run メキキオール (Send Shortcut Keys)
        run: |
          powershell -ExecutionPolicy Bypass -File "scripts/send_shortcut_keys.ps1"
        shell: powershell

      - name: Wait for 5 Minutes
        run: |
          Write-Output "5分間待機中..."
          Start-Sleep -Seconds 300
        shell: powershell

      - name: Check Specific Process
        id: check_process
        run: |
          # Visual Studio のプロセスが実行中か確認します（プロセス名は適宜変更）
          $process = Get-Process -Name "Hutzper.Library" -ErrorAction SilentlyContinue
          if ($process) {
            Write-Output "Hutzper.Library は実行中です。"
          } else {
            Write-Output "Hutzper.Library は停止しています。"
            exit 1
          }
        shell: powershell

      - name: Handle Failure
        if: failure()
        run: echo "プロセスが停止しているため、ジョブが失敗しました。"
