name: Manage and Monitor MS Paint Process

on:
  schedule:
    - cron: '0 22 * * *'    # 22時にプロセスを開始
    - cron: '0 6 * * *'     # 6時にプロセスを終了
    - cron: '*/5 22-23,0-5 * * *' # 5分ごとにプロセスの状態を確認
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (start, stop, check)'
        required: true
        default: 'check'
      time:
        description: 'Time to execute the action'
        required: false

jobs:
  manage-process:
    runs-on: [self-hosted, windows]  # セルフホストランナーとWindows環境を指定

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Manage and Check MS Paint Process
        id: manage_process
        shell: powershell
        run: |
          $Action = "${{ github.event.inputs.action || 'check' }}"
          $Time = if (${{ github.event.inputs.time }}) { [datetime]${{ github.event.inputs.time }} } else { $null }
          .\scripts\manage-and-check-process.ps1 -Action $Action -Time $Time
