name: Manage and Monitor Process

on:
  schedule:
    # 毎日22:00にプロセスを開始するジョブを実行
    - cron: '0 22 * * *'
    # 毎日22:10から6:00までの間で10分ごとにプロセスの状態を確認するジョブを実行
    - cron: '*/10 22-23,0-5 * * *'
    # 毎日6:00にプロセスを終了するジョブを実行
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (start, check, stop)'
        required: true
        default: 'check'
        type: string

jobs:
  start-process:
    if: github.event.schedule.cron == '0 22 * * *' || github.event.inputs.action == 'start'
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run メキキオール (Send Shortcut Keys)
        run: |
          powershell -ExecutionPolicy Bypass -File "scripts/start_process.ps1"
        shell: powershell

  check-process:
    if: github.event.schedule.cron == '*/10 22-23,0-5 * * *' || github.event.inputs.action == 'check'
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Process
        run: |
          powershell -ExecutionPolicy Bypass -File "scripts/check_process.ps1"
        shell: powershell

      - name: Handle Failure
        if: failure()
        run: echo "プロセスが停止しているため、ジョブが失敗しました。"

  stop-process:
    if: github.event.schedule.cron == '0 6 * * *' || github.event.inputs.action == 'stop'
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Stop メキキオール
        run: |
          powershell -ExecutionPolicy Bypass -File "scripts/stop_process.ps1"
        shell: powershell
