name: Build and Run Mekiki

on:
  schedule:
    - cron: '0 22 * * *'  # Start the process every day at 22:00
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (build, run, check, stop)'
        required: false
        default: 'run'
        type: string
      end_time:
        description: 'End time for retry loop (HH:mm format)'
        required: false
        type: string

jobs:
  worked_mekiki:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Prepare Mekiki Directory
        run: |
          $projectDir = "C:\CSharp.Hutzper.Library"
          $repositoryUrl = "https://github.com/Hutzper-inc/CSharp.Hutzper.Library.git"
          $branch = '${{ github.ref_name }}'

          # branchがmainのとき、developに変更（のちに変更）
          if ($branch -eq 'main') {
            $branch = 'develop'
          }
          if (-Not (Test-Path $projectDir)) {
            git clone $repositoryUrl $projectDir
          } else {
            Set-Location -Path $projectDir
            git fetch origin
            git checkout $branch
            git pull origin $branch
          }
        shell: powershell

      - name: Build Project
        run: |
          dotnet build "C:\CSharp.Hutzper.Library\Hutzper.Library.FormsMekiki\Hutzper.Project.Mekiki.csproj" -c Release
        shell: powershell

      - name: Run Mekiki and Check if Mekiki is Alive
        id: check-mekiki-process
        run: |
          Write-Output "Starting Mekiki application..."
          $projectPath = "C:\CSharp.Hutzper.Library\Hutzper.Library.FormsMekiki\Hutzper.Project.Mekiki.csproj"
          Start-Process -FilePath "dotnet" -ArgumentList "run --project `"$projectPath`"" -NoNewWindow -PassThru | Out-Null
          Start-Sleep -Seconds 5

          Write-Output "Checking if Mekiki process is alive..."
          $processName = "Hutzper.Project.Mekiki"
          $startTime = Get-Date
          $endTime = $startTime.AddMinutes(1)
          
          while ((Get-Date) -lt $endTime) {
            $process = Get-Process -Name $processName -ErrorAction SilentlyContinue

            if ($process) {
              Write-Output "$processName is running."
              break
            }
            Start-Sleep -Seconds 5
          }

          if (-Not $process) {
            Write-Output "$processName has stopped within the 1-minute check period."
            exit 1
          }

          Write-Output "Determining end time for process check..."
          if ($env:GITHUB_EVENT_NAME -eq 'schedule') {
            $endTime = (Get-Date).Date.AddHours(6)  # Check until 6:00 the next day
          } else {
            $endTimeString = '${{ github.event.inputs.end_time }}'
            if (-Not $endTimeString) {
              Write-Output "End time is not specified."
              exit 1
            }
            $endTime = [datetime]::ParseExact($endTimeString, 'HH:mm', $null)
            if ($endTime -lt (Get-Date)) {
              $endTime = $endTime.AddDays(1)  # Set to the next day if it's already past the end time
            }
          }

          Write-Output "Checking process status until $endTime..."

          while ((Get-Date) -lt $endTime) {
            Start-Sleep -Seconds 5

            $process = Get-Process -Name $processName -ErrorAction SilentlyContinue
            if (-Not $process) {
              $deadTime = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
              Write-Output "The process stopped at $deadTime."
              exit 1
            }
          }
          Write-Output "The process stayed alive until the specified end time. Ending session."
          exit 0
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        shell: powershell

      - name: Notify GitHub Actions of Result
        run: |
          Write-Output "Process result: Success"
        shell: powershell
